services:

  scanner:
    image: epicsethercatbase
    build:
      context: ./
      dockerfile: docker/epicsEthercatBase/Dockerfile
    
    network_mode: host
    privileged: true
    volumes:
      - /dev:/dev
      - ./tmp/tmuxtmps/scanner/tmp:/tmuxtmp
      - ./tmp:/tmp
    command: ["/bin/bash", "-c", "ethercatctl start && tmux  new -s scanner -d /epics/ethercat/bin/linux-x86_64/scanner -m0 /epics/ethercat/iocs/scanTest/etc/scanner.xml /tmp/socket0 && tmux ls && sleep infinity"]
  scantestioc:
    build:
      context: ./
      dockerfile: docker/scannerTest/Dockerfile
    network_mode: host
    volumes:
      - ./tmp:/tmp
      - ./tmp/tmuxtmps/ioc/tmp:/tmuxtmp
    depends_on:
      - scanner
    command: ["/bin/bash", "-c", "sleep 5 && tmux new-session -s ioc -d ./st.cmd && sleep infinity"]

  