services:
  epicsethercatbase:
    image: epicsethercatbase
    build:
      context: ./
      dockerfile: docker/epicsEthercatBase/Dockerfile
  scanner:
    build:
      context: ./
      dockerfile: docker/epicsEthercatBase/Dockerfile
    
    network_mode: host
    privileged: true
    volumes:
      - /dev:/dev
      - ./tmp:/tmp
    command: ["/bin/bash", "-c", "ethercatctl start && tmux new-session -s scanner -d /epics/ethercat/bin/linux-x86_64/scanner -m0 /epics/ethercat/iocs/scanTest/etc/scanner.xml /tmp/socket0 && sleep infinity"]
  scantestioc:
    build:
      context: ./
      dockerfile: docker/scannerTest/Dockerfile
    network_mode: host
    volumes:
      - /tmp:/tmp
    depends_on:
      - scanner
    command: ["/bin/bash", "-c", "tmux new-session -s ioc -d ./st.cmd && sleep infinity"]

  